# Generated by Django 4.2 on 2024-03-07 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_module', '0047_remove_order_data_which_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('userr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('order_number', models.IntegerField(default=0)),
                ('final_price', models.CharField(blank=True, max_length=2000, null=True)),
                ('count', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_module.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_module.products')),
            ],
        ),
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=300)),
                ('phone_number', models.CharField(max_length=500)),
                ('street_address1', models.CharField(max_length=500)),
                ('town_or_city', models.CharField(max_length=500)),
                ('country_state_or_location', models.CharField(max_length=500)),
                ('post_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('which_order', models.ManyToManyField(default=None, to='order_module.orderdetail')),
                ('which_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
