# Generated by Django 4.2 on 2023-12-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0005_alter_products_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rate',
        ),
        migrations.AddField(
            model_name='add_comments',
            name='rate',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=123, max_length=1000),
            preserve_default=False,
        ),
    ]
