# Generated by Django 4.2 on 2023-12-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0006_remove_products_rate_add_comments_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
