# Generated by Django 4.2 on 2023-12-15 08:41

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0009_remove_add_comments_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='products',
            name='color2',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='products',
            name='color3',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='products',
            name='size_larg',
            field=models.CharField(default=324256, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='size_medium',
            field=models.CharField(default=234, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='size_small',
            field=models.CharField(default=15245, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='size_xlarg',
            field=models.CharField(default=664, max_length=200),
            preserve_default=False,
        ),
    ]
