# Generated by Django 4.2 on 2023-12-15 08:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0010_products_color_products_color2_products_color3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='color2',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='color3',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='size_larg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='size_medium',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='size_small',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='size_xlarg',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
