# Generated by Django 4.2 on 2023-12-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0014_orderdetail_color_orderdetail_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=300)),
                ('phone_number', models.CharField(max_length=500)),
                ('street_address1', models.CharField(max_length=500)),
                ('street_address2', models.CharField(max_length=500)),
                ('town_or_city', models.CharField(max_length=500)),
                ('country_state_or_location', models.CharField(max_length=500)),
                ('post_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('card_name', models.CharField(max_length=100)),
                ('expiration_date', models.CharField(max_length=100)),
                ('cvs', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
