# Generated by Django 4.2 on 2023-12-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0018_orderdetail_coount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_data',
            name='street_address2',
        ),
    ]
