# Generated by Django 4.2 on 2023-12-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0021_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_nimber',
            field=models.IntegerField(default=5345),
            preserve_default=False,
        ),
    ]
