# Generated by Django 4.2 on 2023-12-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0022_orderdetail_order_nimber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_nimber',
            field=models.CharField(),
        ),
    ]
