# Generated by Django 4.2 on 2023-12-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0023_alter_orderdetail_order_nimber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_data',
            name='orderid',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, to='main_module.order'),
            preserve_default=False,
        ),
    ]
