# Generated by Django 4.2 on 2023-12-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0024_order_data_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_data',
            name='orderid',
        ),
    ]
