# Generated by Django 4.2 on 2023-12-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0026_order_data_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_data',
            name='orderid',
        ),
        migrations.AddField(
            model_name='order_data',
            name='whichorder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_module.order'),
        ),
    ]
