# Generated by Django 4.2 on 2023-12-22 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_module', '0027_remove_order_data_orderid_order_data_whichorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_data',
            name='whichorder',
        ),
        migrations.AddField(
            model_name='order_data',
            name='which_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_module.order'),
        ),
        migrations.AddField(
            model_name='order_data',
            name='which_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
