# Generated by Django 4.2 on 2023-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0031_alter_order_payment_date_alter_order_payment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_time',
        ),
        migrations.AddField(
            model_name='order',
            name='order_main_id',
            field=models.CharField(default=35376, max_length=50),
            preserve_default=False,
        ),
    ]
