# Generated by Django 4.2 on 2023-12-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0032_remove_order_payment_time_order_order_main_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
