# Generated by Django 4.2 on 2023-12-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0034_remove_order_order_main_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
