# Generated by Django 4.2 on 2023-12-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0035_remove_order_payment_date_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
