# Generated by Django 4.2 on 2023-12-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0036_remove_order_date_order_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
