# Generated by Django 4.2 on 2023-12-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0038_alter_order_data_which_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_number',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=213),
            preserve_default=False,
        ),
    ]
