# Generated by Django 4.2 on 2023-12-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0039_remove_orderdetail_order_number_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_number',
            field=models.IntegerField(default=23423),
            preserve_default=False,
        ),
    ]
