# Generated by Django 4.2 on 2023-12-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0040_remove_order_order_number_orderdetail_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_data',
            name='which_order',
        ),
        migrations.AddField(
            model_name='order_data',
            name='which_order',
            field=models.ManyToManyField(default=None, to='main_module.orderdetail'),
        ),
    ]
