# Generated by Django 4.2 on 2023-12-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0041_remove_order_data_which_order_order_data_which_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.CharField(blank=True, null=True),
        ),
    ]
