# Generated by Django 4.2 on 2024-03-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0042_alter_orderdetail_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
