# Generated by Django 4.2 on 2024-03-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0045_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='coount',
        ),
    ]
